dataset:
  name: "RTTS"
  root: "./datasets/RTTS/RTTS"
  img_size: 256
  return_bboxes: true
  subset: false

model:
  name: "LFDNet"
  base_channels: 8

evaluation_od:
  device: "cuda"
  use_dehazer: true
  dehazer_checkpoint_path: "pretrained_models\\LFD-Net\\epoch_30_full_ots"
  save_path: "./runs/od_eval/LFDNet_yolov8_tensorrt"
  image_set: "test"
  batch_size: 2
  num_workers: 2
  pin_memory: true
  warmup_runs: 3
  dehazer_input_size: 256
  visualization:
    enabled: true
    num_samples: 12
    seed: 42
    score_thr: 0.5

detector:
  name: "yolov8"
  weights: "./pretrained_models/YOLO/yolov8n.engine" # exported TensorRT engine
  device: "cuda:0"
  conf: 0.001
  iou: 0.5
  imgsz: 512 # should match the export size for a static engine
  max_det: 300
  half: false # runtime info is inferred from the engine; this flag mainly affects .pt inference
