dataset:
  name: "RTTS"
  root: "./datasets/RTTS/RTTS"
  img_size: 256
  return_bboxes: true
  subset: false

model:
  name: "GCANet" # options: AODNet | FFANet | LCANet | LDNet | LFDNet | GCANet | TinyDehazeNet
  base_channels: 8 # relevant for TinyDehazeNet

evaluation_od:
  device: "cuda"
  use_dehazer: true
  #dehazer_checkpoint_path: "./pretrained_models/AOD-Net/epoch3_full_OTS_subset.pth"
  dehazer_checkpoint_path: "pretrained_models/GCA-Net/wacv_gcanet_dehaze.pth"
  save_path: "./runs/od_eval/GCANet_yolov8"
  image_set: "test" # RTTS split file under ImageSets/Main/test.txt
  batch_size: 2
  num_workers: 2
  pin_memory: true
  dehazer_input_size: 256 # set int (e.g. 512) to force fixed dehazer size
  visualization:
    enabled: True
    num_samples: 12
    seed: 42

detector:
  name: "yolov8"
  weights: "./pretrained_models/YOLO/yolov8n.pt"
  device: "cuda:0"
  conf: 0.5
  iou: 0.5
  imgsz: 512
  max_det: 300
